// High-yield MCCQE Part I blueprint topics used to pre-warm the global
// flashcard generation cache. Keep these as learner-facing topic prompts,
// not internal taxonomy keys, because they feed the same generator as manual
// deck creation.

export const MCCQE_BLUEPRINT_TOPICS: readonly string[] = [
  "Chest pain initial assessment",
  "Dyspnea and heart failure",
  "Atrial fibrillation management",
  "Hypertension diagnosis and treatment",
  "Syncope differential diagnosis",
  "Shock recognition and initial management",
  "Acute coronary syndrome",
  "Asthma and COPD exacerbations",
  "Pneumonia diagnosis and treatment",
  "Pulmonary embolism assessment",
  "Abdominal pain approach",
  "Gastrointestinal bleeding",
  "Jaundice and abnormal liver enzymes",
  "Diarrhea and dehydration",
  "Headache red flags",
  "Stroke and TIA initial management",
  "Seizure first presentation",
  "Delirium and altered level of consciousness",
  "Diabetes screening and complications",
  "Thyroid disease interpretation",
  "Acute kidney injury",
  "Anemia workup",
  "Depression and suicide risk",
  "Anxiety disorders",
  "Psychosis and schizophrenia",
  "Substance use disorder",
  "Capacity and consent",
  "Confidentiality and mandatory reporting",
  "Prenatal care and screening",
  "Vaginal bleeding in pregnancy",
  "Hypertensive disorders of pregnancy",
  "Postpartum complications",
  "Pelvic pain and ectopic pregnancy",
  "Amenorrhea approach",
  "Pediatric fever",
  "Failure to thrive",
  "Developmental delay",
  "Pediatric respiratory distress",
  "Immunizations in Canada",
  "Preventive screening guidelines",
  "Breast cancer screening",
  "Cervical cancer screening",
  "Colorectal cancer screening",
  "STI screening and treatment",
  "Falls in older adults",
  "Dementia assessment",
  "Low back pain red flags",
  "Fracture initial management",
  "Acute abdomen surgical causes",
  "Indigenous health and culturally safe care",
];
